ALTER TABLE "Device" ALTER COLUMN "storeId" DROP NOT NULL;
ALTER TABLE "Alert" ALTER COLUMN "storeId" DROP NOT NULL;
ALTER TABLE "Event" ALTER COLUMN "storeId" DROP NOT NULL;

ALTER TABLE "Device" DROP CONSTRAINT IF EXISTS "Device_storeId_fkey";
ALTER TABLE "Alert" DROP CONSTRAINT IF EXISTS "Alert_storeId_fkey";
ALTER TABLE "Event" DROP CONSTRAINT IF EXISTS "Event_storeId_fkey";

ALTER TABLE "Device" ADD CONSTRAINT "Device_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Alert" ADD CONSTRAINT "Alert_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Event" ADD CONSTRAINT "Event_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store"("id") ON DELETE SET NULL ON UPDATE CASCADE;
